site_name: System Administrator Guide
site_url: https://docs.civicrm.org/sysadmin/en/latest/
repo_url: https://lab.civicrm.org/documentation/docs/sysadmin/
edit_uri: https://lab.civicrm.org/documentation/docs/sysadmin/-/edit/master/docs/
site_description: A guide for CiviCRM system administrators.
site_author: The CiviCRM community
theme: 
  name: material
  icon:
    repo: fontawesome/brands/gitlab

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            - startinline: true
  - pymdownx.superfences:
      css_class: codehilite
  - pymdownx.inlinehilite:
      css_class: codehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.details

plugins:
  - search:
      lang: en

nav:
- Home: index.md
- Setup:
  - Setup: setup/index.md
  - Backups: setup/backups.md
  #- Monitoring: setup/monitoring.md
  - Secrets: setup/secret-keys.md
  - Securing your site: setup/security.md
  #- Data migration: setup/migration.md
  - Scheduled jobs: setup/jobs.md
  - Directories: setup/directories.md
  - Caches: setup/cache.md
  - OAuth: setup/oauth.md
  - CiviMail setup:
    - CiviMail setup: setup/civimail/index.md
    - Outbound mail: setup/civimail/outbound.md
    - Inbound mail: setup/civimail/inbound.md
    - Deliverability: setup/civimail/deliverability.md
  - Payment processors:
    - Payment processors: setup/payment-processors/index.md
    - Recurring payments: setup/payment-processors/recurring.md
    - Authorize.net: setup/payment-processors/authorize-net.md
    - Card access: setup/payment-processors/card-access.md
    - First data: setup/payment-processors/first-data.md
    - iATS: setup/payment-processors/iats.md
    - Moneris: setup/payment-processors/moneris.md
    - PayFlow: setup/payment-processors/payflow.md
    - PayJunction: setup/payment-processors/payjunction.md
    - PayPal Standard: setup/payment-processors/paypal-standard.md
    - PayPal Pro and Express: setup/payment-processors/paypal-pro.md
    - Ogone: setup/payment-processors/ogone.md
  - Detailed logging: setup/logging.md
  - Optimizations: setup/optimizations.md
  - Multisite: setup/multisite.md
- Upgrades:
  - Upgrades: upgrade/index.md
  - Upgrade in Drupal 7: upgrade/drupal7.md
  - Upgrade in Drupal 8: upgrade/drupal8.md
  - Upgrade in WordPress: upgrade/wordpress.md
  - Upgrade in Joomla: upgrade/joomla.md
  - Upgrade in Backdrop: upgrade/backdrop.md
  - Version-specific upgrade steps: upgrade/version-specific.md
- Troubleshooting: troubleshooting.md
- Customization:
  #- Basic customization: customize/index.md
  - Extensions: customize/extensions.md
  #- Other languages: customize/i18n.md
  - Override settings: customize/settings.md
  - Override paths: customize/paths.md
  #- Custom development: customize/develop.md
  - Theme information: customize/theme.md
- CMS Integration:
  - Drupal integration:
    - Drupal users, roles and groups integration: integration/drupal/index.md
    - Drupal views: integration/drupal/views.md
    - Webform (Drupal 8): https://docs.civicrm.org/webform-civicrm/en/latest/
    - Webform (Drupal 7): integration/drupal/webform.md
    - WYSIWYG integration: integration/drupal/wysiwyg.md
    - Bootstrap CSS: integration/drupal/bootstrap-css.md
    - Mailhandler: integration/drupal/mailhandler.md
    - Incompatible modules: integration/drupal/incompatibilities.md
  - Backdrop integration:
    - Backdrop users, roles and groups integration: integration/backdrop/index.md
    - Backdrop views: integration/backdrop/views.md
    - Webform: integration/backdrop/webform.md
  - WordPress integration:
    - WordPress integration: integration/wordpress/index.md
    - Base page: integration/wordpress/base-page.md
    - Clean URLs: integration/wordpress/clean-urls.md
    - Forms in WordPress: integration/wordpress/forms.md
    - Plugin integration: integration/wordpress/plugins.md
    - Incompatible plugins: integration/wordpress/incompatibilities.md
  - Joomla integration:
    - Joomla integration: integration/joomla/index.md
    - Dashboard in Joomla: integration/joomla/dashboard.md
    - Forms in Joomla: integration/joomla/forms.md
- Special situations:
  - Staging and production: misc/staging-production.md
  #- Switching installation directories: misc/directories.md
  #- Switching domain names: misc/domain-names.md
  - Switching servers: misc/switch-servers.md
  - Switching CMS:
    - Switch CMS: misc/switching-cms/switch-cms.md
    - Switch from Drupal to Backdrop: misc/switching-cms/drupal-to-backdrop.md
    - Switch from Drupal to Wordpress: misc/switching-cms/drupal-to-wordpress.md
    - Switch from Joomla to Drupal: misc/switching-cms/joomla-to-drupal.md 
  #- Data redaction: misc/redaction.md
